site_name: TF2 HUD Editor
site_author: criticalflaw
theme:
    language: en
    name: material
    logo: resources/logo.png
    favicon: resources/logo.png
    features:
        - navigation.expand
    palette:
        - scheme: default
          primary: indigo
          accent: amber
          toggle:
            icon: material/toggle-switch-off-outline
            name: Switch to dark mode
        - scheme: slate
          primary: amber
          accent: orange
          toggle:
            icon: material/toggle-switch
            name: Switch to light mode
repo_name: GitHub
site_url: https://www.editor.criticalflaw.ca/
repo_url: https://github.com/CriticalFlaw/TF2HUD.Editor/
nav:
    - Home: 'index.md'
    - Screenshots: 'screenshots.md'
    - Troubleshooting: 'troubleshoot.md'
    - How to Contribute: 'contribute.md'
    - Credits: 'credits.md'
    - Adding your HUD:
        - Introduction: 'json/intro.md'
        - Main Settings: 'json/base.md'
        - User Controls: 'json/controls.md'
        - List Options: 'json/options.md'
        - HUD Files: 'json/files.md'
        - HUD Animations: 'json/animations.md'
        - Custom Backgrounds: 'json/backgrounds.md'
hide:
    - toc
google_analytics:
    - G-Q532RTS1WC
    - auto
markdown_extensions:
    - admonition
    - pymdownx.superfences
    - toc:
        toc_depth: 0
plugins:
    - search
    - git-revision-date-localized:
        type: date
extra_css:
    - resources/teamfortress.css
extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/CriticalFlaw/TF2HUD.Editor
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/CriticalFlaw_
        - icon: fontawesome/brands/discord
          link: https://discord.gg/hTdtK9vBhE